/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    FileDisplay: typeof import('./src/components/FileDisplay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OutputLinks: typeof import('./src/components/OutputLinks.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
