version: '3'
services:
  excelmagic-api:
    build:
      context: ./api
    ports:
      - "7000:7000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./api/static:/usr/src/app/static
      - ./api/playground:/usr/src/app/playground
