version: '3'
services:
  excel-magic:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
