version: '3'
services:
  excel-magic-api:
    build:
      context: ./api
    image: inventing.azurecr.io/excel-magic-api:latest
    ports:
      - "7000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  excel-magic-client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: inventing.azurecr.io/excel-magic-client:latest
    ports:
      - "80"
    restart: unless-stopped
